### ISSUE TITLE
Can't use ERB in config/critical_path_css.yml

### ISSUE THREAD

**Issue by bbuchalter** [mudbugmedia/critical-path-css-rails#13]
We have many different base URLs for different staging environments. We record this in an environment variable. Ideally, I could use ERB to access that variable in the `config/critical_path_css.yml` file.

**Comment by michael-misshore** [comment]
@bbuchalter, Forgive me if I'm misunderstanding the issue, but I believe this has been address in PR #9. Let me know if that solves this issue. With that being said, I believe we still need to add documentation for this in the README.

A side note, there will be an additional way of adding routes with PR #11. I should be getting that merged in soon, hopefully.

**Comment by bbuchalter** [comment]
Thanks for the quick reply and your contribution to open source! ❤️ 

Out of habit (and to get my editor to do syntax highlighting) I renamed the file `config/critical_path_css.yml.erb` which of course resulted in an error because the file path is hard-coded. If we intend this file to use ERB, perhaps renaming the hardcode? Maybe better documentation is all that's in order?

**Comment by michael-misshore** [comment]
@bbuchalter, I think it makes sense to keep things consistent with existing rails conventions for now, namely `database.yml`. In most editors, you should be able to toggle what syntax highlighting you want for a particular file, so you should be able to get the desired behavior without renaming. I think we should leave the filename as is for now and document that the YAML file supports ERB.

I'll close this for now, but if more people believe we should rename the file, I can open this back up.

**Comment by randallreedjr** [comment]
I know this has been closed for a long time, but, for what it's worth, I agree with supporting both filenames.
