### ISSUE TITLE
Upgrade Penthouse

### ISSUE THREAD

**Issue by jackcompton** [mudbugmedia/critical-path-css-rails#21]
Are there any plans to upgrade to the latest version of penthouse?

**Comment by michael-misshore** [comment]
Yes. I've started work on this a few weeks back, but haven't had a chance to wrap up the update.

**Comment by jackcompton** [comment]
How can I help?

**Comment by michael-misshore** [comment]
If you're comfortable with the code base, I *think* the only thing I needed to do was test.

I've pushed my changes to the `update-penthouse-1.0` branch here: https://github.com/mudbugmedia/critical-path-css-rails/tree/update-penthouse-1.0

If you want to fork the project, checkout that branch, and ensure everything is working correctly, that would be a huge help!

**Comment by michael-misshore** [comment]
Looks like Penthouse went to `1.2.0` since my last commit. Feel free to update to `1.2.0` instead of `1.1.0`.

**Comment by juampi** [comment]
How is this coming along? What else needs to be done, and how can we help?

By the way, the latest version is now `1.3.0`.

**Comment by michael-misshore** [comment]
@juampi I had some time to work on this a few days ago, but I had some trouble testing this on my application. I started to implement a docker ENV and test suite, but I haven't finished it yet.

https://github.com/mudbugmedia/critical-path-css-rails/commit/e8b768b0d03d90e11fbfda730ee0b2db923a6b3a

The above link is my last commit (The upgrade to 1.3.0). I'd have no issues merging this to master and pushing this if I can confirm that this branch is stable. Testing would be a huge help.

**Comment by michael-misshore** [comment]
I'm closing this as #24 has addressed this issue.
