### ISSUE TITLE
clear_matched does not work with Dalli/Memcached

### ISSUE THREAD

**Issue by randallreedjr** [mudbugmedia/critical-path-css-rails#30]
The Dalli Memcached client expects `delete_matched!` instead of `clear_matched`.

**Comment by michael-misshore** [comment]
This issue is already referenced in the readme.

> NOTE: The clear_matched method will not work with Memcached due to the latter's incompatibility with Rails' delete_matched method. We recommend using an alternative cache such as Redis.

Closing this issue.
