### ISSUE TITLE
Error without declared css_path/css_paths

### ISSUE THREAD

**Issue by mrusa** [mudbugmedia/critical-path-css-rails#38]
When using version 3 without declaring `css_path` and `css_paths` in the yaml config (using only manifest_name), the following error occurs when trying to generate critical css via rake task: 

`undefined method collect for nil`

It's coming from this line https://github.com/mudbugmedia/critical-path-css-rails/blob/master/lib/critical_path_css/rails/config_loader.rb#L27

I'm using Rails 5.2.2. When downgrading the gem to 2.10.1 this error does not occur anymore.

I hope this helps and thanks for your work.

**Comment by michael-misshore** [comment]
@mrusa Thanks for the report. I know exactly how to fix this, but it may be a few days until I can get to it. I'll try to fix it tonight, however.

With that being said, you can use the latest version by setting the css_path if you really want to/need to update to version 3.

**Comment by michael-misshore** [comment]
#39 fixes this issue. Please update to 3.0.1 or later.
