### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by rikkipitt** [mudbugmedia/critical-path-css-rails#45]
Hi folks,

I've added this to my Rails project using the default settings in the README but when I generate, I run into an issue where the CSS in my project is not found. It does exist though...

Any ideas? Thanks!

```shell
rake critical_path_css:generate
```
**Error: ENOENT: no such file or directory**, open '/assets/application-d02df3cf214bde099b3a0207da21c2d9a9d5a328b1f3631ac6da62497a938264.css'
Failed to get CSS for route /
  with options={"url"=>"http://xero-calendar.test/", "css"=>"/assets/application-d02df3cf214bde099b3a0207da21c2d9a9d5a328b1f3631ac6da62497a938264.css", "width"=>1300, "height"=>900, "timeout"=>30000, "forceInclude"=>[], "strict"=>false, "maxEmbeddedBase64Length"=>1000, "userAgent"=>"Penthouse Critical Path CSS Generator", "renderWaitTime"=>100, "blockJSRequests"=>true, "customPageHeaders"=>{"Accept-Encoding"=>"identity"}}

**Comment by rikkipitt** [comment]
The same issue happens on Heroku. Everything installs okay. I'm using the heroku/node and https://github.com/heroku/heroku-buildpack-google-chrome buildpacks before heroku/ruby.

**Comment by saiwas** [comment]
I got the same issue here. Is there any update on this issue?

**Comment by rikkipitt** [comment]
Hi @saiwas, I'm afraid I didn't find a solution to the above. However, I did find that if you remove the `manifest_name` and use `css_path` instead, it works... 

E.g.

```yml
defaults: &defaults
  css_path: /assets/application.css`
```

Off the top of my head, the [non-stupid-digest-assets](https://github.com/alexspeller/non-stupid-digest-assets) gem might be required to allow you to call the asset file without a digest though.

**Comment by Sgemini** [comment]
@rikkipitt when i have any css update, i need to run `rake assets:precompile` before generate. it make me works.

**Comment by Sgemini** [comment]
@rikkipitt i change the code on `config_loader.rb ` , it works for me

```
config['css_paths'] = [format_path(ActionController::Base.helpers.stylesheet_path(config['manifest_name'], host: ''))]
```

**Comment by michael-misshore** [comment]
@rikkipitt @Sgemini , I'm pretty sure you should only be using one of the following options: `manifest_name`, `css_path', or `css_paths`. I'll write a test to confirm this issue, follow up with adding a clear exceptions, and update the documentation. Thanks for reporting this issue

**Comment by michael-misshore** [comment]
PR #48 addresses this issue
