### ISSUE TITLE
Using built-in Rails cache can cause various issues

### ISSUE THREAD

**Issue by ProGM** [mudbugmedia/critical-path-css-rails#8]
I noticed that you're using built-in rails cache to store extract critical css.

This can be problematic when using [`redis-cache-store`](https://github.com/redis-store/redis-rails), because it's default `expires_in` value is set to 90 minutes.

A solution could be to pass explicitly `expires_in: 0` to `Rails.cache.write`.

**Comment by michael-misshore** [comment]
@ProGM, Could you possibly set the `expires_in` to 0 when setting the `cache_store` in `config/application.rb` as shown under the Usage section in the Readme?

```# config/application.rb
config.cache_store = :redis_store, "redis://localhost:6379/0/cache", { expires_in: 90.minutes }```

If this doesn't work, I can certainly add the expires_in on the `Rails.cache.write`

**Comment by ProGM** [comment]
First of all, I made a mistake: Setting it to 0 returns me a redis error: `ERR invalid expire time in setex`.

I did some tests, and I realized that I get the expected behavior by passing `expires_in: nil`.

Then... Yes, of course, I can set it globally, but since it's a global settings, I have to change all values in my cache fragments to `90.minutes` to keep the current behavior.

**Comment by michael-misshore** [comment]
Ah, the issue with setting it globally does make sense.

I'll test out the `nil` fix tonight, and should hopefully have that pushed up with updated documentation.

Thanks for your contributions!
